version: '3.7'

services:

  web:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html:rw
      - type: bind
        source: "/data/sphinx/docker-compose/conf/ssl.conf"
        target: "/etc/nginx/conf.d/default.conf"
        volume:
          nocopy: true
      - type: bind
        source: "/data/docker-compose/keys/ssl.key"
        target: "/etc/nginx/ssl/ssl.key"
        volume:
          nocopy: true
      - type: bind
        source: "/data/docker-compose/keys/ssl.cer"
        target: "/etc/nginx/ssl/ssl.cer"
        volume:
          nocopy: true
      - type: bind
